blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("blogs", views.blogList, name="blogList"),
    path("readBlog/<int:id>/", views.readBlog, name="readBlog"),
    path("bdel/<int:id>/", views.deleteBlog, name="bDel"),
    path("cdel/<int:id>/<int:bid>/", views.deleteCom, name="cDel"),
    path("blike/<int:id>/", views.blike, name="blike"),
    path("bdlike/<int:id>/", views.bdlike, name="bdlike"),
]

blog/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

class Blog(models.Model):
    #Title of the Blog
    title = models.CharField(max_length=150)
    
    #Date the Blog was originally posted auto set by the view
    date_posted = models.DateTimeField()

    #Date the Blog was last edited. 
    #Will initially be blank until the author edits the Blog 
    #then will be set the same as date posted
    date_last_edited = models.DateTimeField(blank=True, null=True)

    #The text content of the Blog post
    content = models.TextField(max_length=3000)

    #snippet of blog content to be displayed on home page
    cont_prev = models.CharField(max_length=80, default="")

    #The user that created the Blog
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    #for URL readability
    slug = models.SlugField(default="", null=False)

    def __str__(self):
        return self.title
    
    def was_posted_recently(self):
        return self.date_posted >= timezone.now() - datetime.timedelta(days=1)
    
    def setPostDate(self):
        self.date_posted = timezone.now()

    def setEditDate(self, dt):
        self.date_last_edited = dt

    def setAuthor(self, user):
        self.author = user    

    def setContPrev(self):
        self.cont_prev = self.content[0:77] + "..."
    


class Comment(models.Model):
    #the user that created the comment
    cAuthor = models.ForeignKey(User, on_delete=models.CASCADE)

    #the blog the comment is attached to
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

    #the text content of the comment
    content = models.TextField(max_length=250)
    
    #date the comment was posted
    date_posted = models.DateTimeField()
    

    def __str__(self):
        return self.content
    
    def setBlog(self, blog):
        self.blog = blog  
    
    def setAuthor(self, user):
        self.cAuthor = user  

    def setPostDate(self):
        self.date_posted = timezone.now()
    
    def was_posted_recently(self):
        return self.date_posted >= timezone.now() - datetime.timedelta(days=1)
    
class Blike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

class Clike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    com = models.ForeignKey(Comment, on_delete=models.CASCADE)

class Bdislike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

class Cdislike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    com = models.ForeignKey(Comment, on_delete=models.CASCADE)

blog/forms.py
from django import forms
from .models import Blog, Comment

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields =["title", "content"]

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]
    

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from .models import Blog, Comment, Blike, Bdislike, Clike, Cdislike
from .forms import BlogForm, CommentForm
# Create your views here.
def home(request):
    blogs = Blog.objects.all()
    context = {'blogs': blogs}

    return render(request, 'home.html', context)

def blogList(request):
    if request.user.is_authenticated:
        blogs = Blog.objects.filter(author=request.user)
        if request.method == "POST":
            form = BlogForm(request.POST)
            if form.is_valid():
                nb = form.save(commit=False)
                nb.setPostDate()
                nb.setAuthor(request.user)
                nb.setContPrev()
                nb.save()
        else:
            form = BlogForm()
        context = {'blogs': blogs, 'form': form}
        return render(request, 'blogList.html', context)
        
    else:
        return redirect('user:login')
    
def readBlog(request, id):
    if request.user.is_authenticated:
        if request.method == "POST":
            form = CommentForm(request.POST)
            if form.is_valid():
                nc = form.save(commit=False)
                nc.setAuthor(request.user)
                nc.setBlog(Blog.objects.get(pk=id))
                nc.setPostDate()
                nc.save()
        else:
            form = CommentForm()
        try:
            b = Blog.objects.get(pk=id)
            coms = b.comment_set.all()

        except ObjectDoesNotExist:
            return redirect('home')
        
        context = {'blog': b, 'coms': coms, 'form': form}
        return render(request, 'readBlog.html', context)
    else:
        try:
            b = Blog.objects.get(pk=id)
            coms = b.comment_set.all()
            context = {'blog': b, 'coms': coms}
            
            return render(request, 'readBlog.html', context)
        
        except ObjectDoesNotExist:
            return redirect('home')
    
    
def deleteBlog(request, id):
    if request.user.is_authenticated:
        b = Blog.objects.get(pk=id)
        if b.author == request.user:
            b.delete()
            return redirect('blogList')
        else:
            return redirect('home')
    else:
        return redirect('user:login')
    
def deleteCom(request, id, bid):
    if request.user.is_authenticated:
        c = Comment.objects.get(pk=id)
        if c.cAuthor == request.user:
            c.delete()
            return redirect(reverse('blogList', kwargs={'id': bid}))
        else:
            return redirect('home')
    else:
        return redirect('user:login')

def blike(request, id):
    if request.user.is_authenticated:
        b = Blog.objects.get(pk=id)
        try:
            bl = Blike.objects.get(user=request.user, blog=b)
            bl.delete()
        except ObjectDoesNotExist:
           nbl = Blike(user=request.user, blog=b)
           nbl.save()

        try:
            bd = Bdislike.objects.get(user=request.user, blog=b)
            bd.delete()
        except ObjectDoesNotExist:
            pass

        return redirect('home')
    else:
        return redirect('home')
    
def bdlike(request, id):
    if request.user.is_authenticated:
        b = Blog.objects.get(pk=id)
        try:
            bd = Bdislike.objects.get(user=request.user, blog=b)
            bd.delete()
        except ObjectDoesNotExist:
            nbd = Bdislike(user=request.user, blog=b)
            nbd.save()

        try:
            bl = Blike.objects.get(user=request.user, blog=b)
            bl.delete()
        except ObjectDoesNotExist:
            pass 

        return redirect('home')
    else:
        return redirect('home')

blog/templates/base.html

<!doctype html>
<html lang="en" data-bs-theme="dark">
  <head>
    <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </head>
  
  <body data-bs-spy="scroll" >
    {% include 'navbar.html' %}
    <br>
    
    {% block content %}

    {% endblock %}
    
  </body>
</html>


blog/templates/blogList.html
{% extends "base.html" %}
    
{% block content %}   

<div class="container">
    <div class="row">
{%for b in blogs%}
        <div class="col-6 ">
            <div class="card" style="width: 18rem;">
                <div class="card-header">{{b.author.username}}</div>
                <div class="card-body">
                    <h5><a href="{%url 'readBlog' b.id %}"class="card-title">{{b.title}}</a></h5>
                    {%if b.date_last_edited%}
                    <h6 class="card-subtitle text-body-secondary">{{b.date_posted}}</h6>
                    <p class="card-subtitle mb-2 text-body-secondary">{{b.date_last_edited}}</p>
                    {%else%}
                    <h6 class="card-subtitle mb-2 text-body-secondary">{{b.date_posted}}</h6>
                    {%endif%}
                    <p class="card-text">{{b.cont_prev}}</p>
                    <a href="{%url 'bDel' b.id %}" class="btn btn-outline-danger">Delete</a>
                </div>
            </div>
        </div>
    
{%endfor%} 
        <button type="button" class="btn btn-outline-info" data-bs-toggle="modal" data-bs-target="#blogcreate"> + </button>
    </div>   
</div>



<!-- Create Modal -->
<div class="modal fade" id="blogcreate" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h1 class="modal-title fs-5" id="staticBackdropLabel">Create a New Blog</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-outline-success">Create</button>
            </form>
            <br>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
    </div>
</div>
{% endblock %}

blog/templates/home.html
{% extends "base.html" %}
    
{% block content %}   
{%if request.user.is_authenticated%}
<h1> Logged in </h1>
{%else%}
<h1> Not Logged in </h1>
{%endif%}
<div class="container">
{%for b in blogs%}

    <div class="card" style="width: 18rem;">
        <div class="card-header">{{b.author.username}}</div>
        <div class="card-body">
            <h5><a href="{%url 'readBlog' b.id %}"class="card-title">{{b.title}}</a></h5>
            {%if b.date_last_edited%}
            <h7 class="card-subtitle text-body-secondary">{{b.date_posted}}</h7>
            <p class="card-subtitle mb-2 text-body-secondary">{{b.date_last_edited}}</p>
            {%else%}
            <p class="card-subtitle mb-2 text-body-secondary">{{b.date_posted}}</p>
            {%endif%}
            <p class="card-text">{{b.cont_prev}}</p>
            {%if request.user.is_authenticated%}
            <a href="{%url 'blike' b.id%}" class="btn text-success">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-up" viewBox="0 0 16 16">
                    <path d="M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v4.001c0 .845.682 1.464 1.448 1.545 1.07.114 1.564.415 2.068.723l.048.03c.272.165.578.348.97.484.397.136.861.217 1.466.217h3.5c.937 0 1.599-.477 1.934-1.064a1.86 1.86 0 0 0 .254-.912c0-.152-.023-.312-.077-.464.201-.263.38-.578.488-.901.11-.33.172-.762.004-1.149.069-.13.12-.269.159-.403.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2 2 0 0 0-.138-.362 1.9 1.9 0 0 0 .234-1.734c-.206-.592-.682-1.1-1.2-1.272-.847-.282-1.803-.276-2.516-.211a10 10 0 0 0-.443.05 9.4 9.4 0 0 0-.062-4.509A1.38 1.38 0 0 0 9.125.111zM11.5 14.721H8c-.51 0-.863-.069-1.14-.164-.281-.097-.506-.228-.776-.393l-.04-.024c-.555-.339-1.198-.731-2.49-.868-.333-.036-.554-.29-.554-.55V8.72c0-.254.226-.543.62-.65 1.095-.3 1.977-.996 2.614-1.708.635-.71 1.064-1.475 1.238-1.978.243-.7.407-1.768.482-2.85.025-.362.36-.594.667-.518l.262.066c.16.04.258.143.288.255a8.34 8.34 0 0 1-.145 4.725.5.5 0 0 0 .595.644l.003-.001.014-.003.058-.014a9 9 0 0 1 1.036-.157c.663-.06 1.457-.054 2.11.164.175.058.45.3.57.65.107.308.087.67-.266 1.022l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.414-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.047.047.109.177.005.488a2.2 2.2 0 0 1-.505.805l-.353.353.353.354c.006.005.041.05.041.17a.9.9 0 0 1-.121.416c-.165.288-.503.56-1.066.56z"/>
                </svg>
                {{b.blike_set.all.count}}
            </a>
            <a href="{%url 'bdlike' b.id%}" class="btn text-danger">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-down" viewBox="0 0 16 16">
                    <path d="M8.864 15.674c-.956.24-1.843-.484-1.908-1.42-.072-1.05-.23-2.015-.428-2.59-.125-.36-.479-1.012-1.04-1.638-.557-.624-1.282-1.179-2.131-1.41C2.685 8.432 2 7.85 2 7V3c0-.845.682-1.464 1.448-1.546 1.07-.113 1.564-.415 2.068-.723l.048-.029c.272-.166.578-.349.97-.484C6.931.08 7.395 0 8 0h3.5c.937 0 1.599.478 1.934 1.064.164.287.254.607.254.913 0 .152-.023.312-.077.464.201.262.38.577.488.9.11.33.172.762.004 1.15.069.13.12.268.159.403.077.27.113.567.113.856s-.036.586-.113.856c-.035.12-.08.244-.138.363.394.571.418 1.2.234 1.733-.206.592-.682 1.1-1.2 1.272-.847.283-1.803.276-2.516.211a10 10 0 0 1-.443-.05 9.36 9.36 0 0 1-.062 4.51c-.138.508-.55.848-1.012.964zM11.5 1H8c-.51 0-.863.068-1.14.163-.281.097-.506.229-.776.393l-.04.025c-.555.338-1.198.73-2.49.868-.333.035-.554.29-.554.55V7c0 .255.226.543.62.65 1.095.3 1.977.997 2.614 1.709.635.71 1.064 1.475 1.238 1.977.243.7.407 1.768.482 2.85.025.362.36.595.667.518l.262-.065c.16-.04.258-.144.288-.255a8.34 8.34 0 0 0-.145-4.726.5.5 0 0 1 .595-.643h.003l.014.004.058.013a9 9 0 0 0 1.036.157c.663.06 1.457.054 2.11-.163.175-.059.45-.301.57-.651.107-.308.087-.67-.266-1.021L12.793 7l.353-.354c.043-.042.105-.14.154-.315.048-.167.075-.37.075-.581s-.027-.414-.075-.581c-.05-.174-.111-.273-.154-.315l-.353-.354.353-.354c.047-.047.109-.176.005-.488a2.2 2.2 0 0 0-.505-.804l-.353-.354.353-.354c.006-.005.041-.05.041-.17a.9.9 0 0 0-.121-.415C12.4 1.272 12.063 1 11.5 1"/>
                </svg>
                {{b.bdislike_set.all.count}}
            </a>
            {%else%}
            <a href="" class="btn text-success">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-up" viewBox="0 0 16 16">
                    <path d="M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v4.001c0 .845.682 1.464 1.448 1.545 1.07.114 1.564.415 2.068.723l.048.03c.272.165.578.348.97.484.397.136.861.217 1.466.217h3.5c.937 0 1.599-.477 1.934-1.064a1.86 1.86 0 0 0 .254-.912c0-.152-.023-.312-.077-.464.201-.263.38-.578.488-.901.11-.33.172-.762.004-1.149.069-.13.12-.269.159-.403.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2 2 0 0 0-.138-.362 1.9 1.9 0 0 0 .234-1.734c-.206-.592-.682-1.1-1.2-1.272-.847-.282-1.803-.276-2.516-.211a10 10 0 0 0-.443.05 9.4 9.4 0 0 0-.062-4.509A1.38 1.38 0 0 0 9.125.111zM11.5 14.721H8c-.51 0-.863-.069-1.14-.164-.281-.097-.506-.228-.776-.393l-.04-.024c-.555-.339-1.198-.731-2.49-.868-.333-.036-.554-.29-.554-.55V8.72c0-.254.226-.543.62-.65 1.095-.3 1.977-.996 2.614-1.708.635-.71 1.064-1.475 1.238-1.978.243-.7.407-1.768.482-2.85.025-.362.36-.594.667-.518l.262.066c.16.04.258.143.288.255a8.34 8.34 0 0 1-.145 4.725.5.5 0 0 0 .595.644l.003-.001.014-.003.058-.014a9 9 0 0 1 1.036-.157c.663-.06 1.457-.054 2.11.164.175.058.45.3.57.65.107.308.087.67-.266 1.022l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.414-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.047.047.109.177.005.488a2.2 2.2 0 0 1-.505.805l-.353.353.353.354c.006.005.041.05.041.17a.9.9 0 0 1-.121.416c-.165.288-.503.56-1.066.56z"/>
                </svg>
                {{b.blike_set.all.count}}
            </a>
            <a href="" class="btn text-danger">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-down" viewBox="0 0 16 16">
                    <path d="M8.864 15.674c-.956.24-1.843-.484-1.908-1.42-.072-1.05-.23-2.015-.428-2.59-.125-.36-.479-1.012-1.04-1.638-.557-.624-1.282-1.179-2.131-1.41C2.685 8.432 2 7.85 2 7V3c0-.845.682-1.464 1.448-1.546 1.07-.113 1.564-.415 2.068-.723l.048-.029c.272-.166.578-.349.97-.484C6.931.08 7.395 0 8 0h3.5c.937 0 1.599.478 1.934 1.064.164.287.254.607.254.913 0 .152-.023.312-.077.464.201.262.38.577.488.9.11.33.172.762.004 1.15.069.13.12.268.159.403.077.27.113.567.113.856s-.036.586-.113.856c-.035.12-.08.244-.138.363.394.571.418 1.2.234 1.733-.206.592-.682 1.1-1.2 1.272-.847.283-1.803.276-2.516.211a10 10 0 0 1-.443-.05 9.36 9.36 0 0 1-.062 4.51c-.138.508-.55.848-1.012.964zM11.5 1H8c-.51 0-.863.068-1.14.163-.281.097-.506.229-.776.393l-.04.025c-.555.338-1.198.73-2.49.868-.333.035-.554.29-.554.55V7c0 .255.226.543.62.65 1.095.3 1.977.997 2.614 1.709.635.71 1.064 1.475 1.238 1.977.243.7.407 1.768.482 2.85.025.362.36.595.667.518l.262-.065c.16-.04.258-.144.288-.255a8.34 8.34 0 0 0-.145-4.726.5.5 0 0 1 .595-.643h.003l.014.004.058.013a9 9 0 0 0 1.036.157c.663.06 1.457.054 2.11-.163.175-.059.45-.301.57-.651.107-.308.087-.67-.266-1.021L12.793 7l.353-.354c.043-.042.105-.14.154-.315.048-.167.075-.37.075-.581s-.027-.414-.075-.581c-.05-.174-.111-.273-.154-.315l-.353-.354.353-.354c.047-.047.109-.176.005-.488a2.2 2.2 0 0 0-.505-.804l-.353-.354.353-.354c.006-.005.041-.05.041-.17a.9.9 0 0 0-.121-.415C12.4 1.272 12.063 1 11.5 1"/>
                </svg>
                {{b.bdislike_set.all.count}}
            </a>
            {%endif%}
            
        </div>
    </div>

<br>
{%endfor%}    
</div>
{% endblock %}

blog/templates/navbar.html
<header class="navbar navbar-expand-lg bd-navbar sticky-top bg-body-secondary">
  <nav class="container-xxl bd-gutter flex-wrap flex-lg-nowrap">
    <a class="navbar-brand" href="">Blog</a>
    <div class="offcanvas-lg offcanvas-end flex-grow-1" tabindex="-1" id="bdNavbar" data-bs-scroll="true">
      <div class="offcanvas-body p-4 pt-0 p-lg-0">
        <hr class="d-lg-none text-white-50">
        <ul class="navbar-nav flex-row flex-wrap bd-navbar-nav">
          <li class="nav-item col-6 col-lg-auto">
            <a class="nav-link btn" href="{%url 'home' %}" >Home</a>
          </li>
          <li class="nav-item col-6 col-lg-auto">
            <a class="nav-link btn" href="{%url 'blogList' %}" >My Blogs</a>
          </li>
          <li class="nav-item col-6 col-lg-auto">
            <a class="nav-link btn" href="" >My Photo Libraries</a>
          </li>
        </ul>
        <ul class="navbar-nav flex-row flex-wrap ms-md-auto justify-content-center">
          <form class="d-flex me-2" role="search">
            <div class="input-group mb-3">
              <input type="search" class="form-control " placeholder="Search Blogs/Authors" aria-label="Search" aria-describedby="button-addon2">
              <button class="btn btn-outline-secondary" type="button" id="button-addon2">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                  <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
                </svg>
              </button>
            </div>
          </form>
        </ul>
        
        <ul class="navbar-nav flex-row flex-wrap ms-md-auto">
          {%if user.is_authenticated%}
          <li class="nav-item dropdown">
            <button class="btn btn-link nav-link py-2 px-0 px-lg-2 dropdown-toggle d-flex align-items-center" type="button" data-bs-toggle="dropdown" aria-expanded="false"
              data-bs-display="static"> <img src="{{request.user.userimg.prof_img.url}}" class="me-2" style="height:25px; width:25px;"/> {{user.username}} 
            </button>
            <ul class="dropdown-menu dropdown-menu-end">
              <li><a class="dropdown-item" href="{%url 'user:login'%}">View Profile</a></li>
              <li><a class="dropdown-item text-danger" href="{% url 'user:logout'%}">Logout</a></li>
            </ul>
          </li>
          {%else%}
          <li class="nav-item col-6 col-lg-auto">
            <a class="nav-link btn" href="{%url 'user:login' %}" >Login</a>
          </li>
          {%endif%}
        </ul>
      </div>
    </div>
  </nav>
</header>
      

blog/templates/readBlog.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}   

<div class="container ">
    <div class="row border-top  border-white">
        <div class="col-3 border-end border-white">
            <!--Left side bar with something -->
            <p>something</p>
        </div>

        <div class="col-6">
            <br>
            <h5><a href="{%url 'readBlog' blog.id %}"class="card-title">{{blog.title}}</a></h5>
            {%if blog.date_last_edited%}
            <h6 class="card-subtitle text-body-secondary">{{blog.date_posted}}</h6>
            <p class="card-subtitle mb-3 text-body-secondary">Edited:{{blog.date_last_edited}}</p>
            {%else%}
            <h6 class="card-subtitle mb-3 text-body-secondary">{{blog.date_posted}}</h6>
            {%endif%}
            <p class="card-text" style="white-space: pre-wrap">{{blog.content}}</p>
            <br>
            <br>
            <h4 class="card-title border-top border-white">Comments</h4>
            <br>
            {%for c in coms%}
            <h5 class="card-title"> {{c.cAuthor.username}}</h5>
            <p class="card-subtitle"> {{c.date_posted}}</p>
            <p class="card-text" style="white-space: pre-wrap"> {{c.content}}</p>
            <a href="{%url 'cDel' c.id blog.id%}" class="btn btn-outline-danger">Delete</a>
            {%endfor%}
            <br>
            <form enctype="multipart/form-data" method="post">
                {%csrf_token%}
                {% render_field form.content type="textarea" placeholder="Comment..." class+="form-control"%}
                <input type="hidden" value="{{blog.id}}" name="blog">
                <button type="submit" class="btn btn-outline-success">Post</button>
            </form>
        </div>

        <div class="col-3 border-start border-white">
            <!--Author details-->
            <br>
            <h5>Author: {{blog.author.username}}</h5>
        </div>
    </div>



</div>
{% endblock %}