users/urls.py
from django.urls import path

from . import views

app_name = "user"
urlpatterns = [
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('register/', views.register_user, name="register_user"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserImg(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    prof_img = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.user.username

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField() 
    prof_img = forms.ImageField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password1'].help_text = None

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'prof_img')

class EditUserForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField() 
    prof_img = forms.ImageField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].label = 'First Name'
        self.fields['last_name'].label = 'Last Name'
        self.fields['prof_img'].label = 'Profile Image'

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'prof_img')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from .forms import SignUpForm
from .models import UserImg
# Create your views here.
def login_user(request):
    if request.method == "POST":
        email = request.POST['userEmail']
        pswd = request.POST['userPswd']
        user = authenticate(request, username=email, password=pswd)

        if user is not None:
            login(request, user)
            return redirect("home")
        else:
            message = "The username/password entered is incorrect. Please try again."
            return render(request, 'authenticate/login.html', {'message': message})
    else:
        return render(request, 'authenticate/login.html', {})
    
def logout_user(request):
    logout(request)
    messages.success(request, ("You were successfully logged out."))
    return redirect("home")

def register_user(request):
    if request.method == "POST":
        form = SignUpForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password1"]
            user = authenticate(username=username, password=password)
            if request.FILES:
               UserImg.objects.create(user=user, prof_img=request.FILES['prof_img'])
            login(request, user)
            return redirect("home")
        
    else:
        form = SignUpForm()
    
    return render(request, 'authenticate/register_user.html', {'form':form,})

users/templates/authenticate/base.html
<!doctype html>
<html lang="en" data-bs-theme="dark">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CMS</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </head>
  <body class="container-fluid">
    
    <br>
    {% block content %}

    {% endblock %}
    
  </body>
</html>


users/templates/authenticate/login.html
{% extends "authenticate/base.html" %}

    
    {% block content %}   
        <div class="conatiner-sm text-center" >
            <br>
            <br>
            <div class="row">
                <div class="col">
                </div>

                <div class="col bg-body-secondary border border-light-border-subtle rounded-3"> 
                    <h1>CMS Login</h1>
                    <form action="" method="post">
                        {% csrf_token %}
                        {% if message %}
                        <div class="row mb-3">
                            <ul class="text-danger-emphasis"> {{message}} </ul>
                        </div>
                        {% endif %}
                        <br>
                        <input type="text" class="form-control" name="userEmail" placeholder="Username">
                        <br>
                        <input type="password" class="form-control" name="userPswd" placeholder="Password">
                        <br>
                        <input type="submit" value="Login" class=" btn btn-outline-success">
                        <a href="{% url 'user:register_user' %}" >Don't have an account?</a>
                    </form>        
                    <br>
                </div>

                <div class="col">
                </div>
            </div>
        </div>
    {% endblock %}

users/templates/authenticate/register_user.html
{% extends "authenticate/base.html" %}
    {% load widget_tweaks %}
    
    {% block content %} 
        <div class="conatiner">
            <div class="row">
                <div class="col">
                </div>
                <div class="col bg-body-secondary border border-light-border-subtle rounded-3">
                    <br>
                    <h1>Register</h1>
                    <br>
                    <form enctype="multipart/form-data" method="post">
                        {% csrf_token %}
                        {% render_field form.username type="text" placeholder="Username" class+="form-control"%}
                        <br>
                        {% render_field form.first_name type="text" placeholder="First Name" class+="form-control"%}
                        <br>
                        {% render_field form.last_name type="text" placeholder="Last Name" class+="form-control"%}
                        <br>
                        {% render_field form.email type="email" placeholder="Email" class+="form-control"%}
                        <br>
                        {% render_field form.password1 type="password" placeholder="Password" class+="form-control"%}
                        <br>
                        {% render_field form.password2 type="password" placeholder="Confirm Password" class+="form-control"%}
                        <br>
                        <label class="form-label">Profile Image</label>
                        {% render_field form.prof_img type="file" placeholder="Profile Image" class+="form-control"%}
                        <br>
                        <input type="submit" value="Register" class="btn btn-outline-success">
                        <a href="{%url 'user:login' %}" class="btn btn-outline-danger">Cancel</a>
                    </form>
                    <br>
                </div>
                <div class="col">
                </div>
            </div>
        </div>
    {% endblock %}